import supabase from './db-client.js';

function ident(name) {
  const cleaned = String(name || 'Saga')
    .replace(/[^A-Za-z0-9]+/g, ' ')
    .trim()
    .split(/\s+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');
  return cleaned || 'Saga';
}

function camel(name) {
  const p = ident(name);
  return p.charAt(0).toLowerCase() + p.slice(1);
}

function toYaml(value, indent = 0) {
  const pad = '  '.repeat(indent);
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (typeof value === 'string') {
    if (value === '' || /[:#\n\-]/.test(value) || value.includes('"')) {
      return JSON.stringify(value);
    }
    return value;
  }
  if (Array.isArray(value)) {
    if (!value.length) return '[]';
    return value
      .map((item) => {
        if (item && typeof item === 'object') {
          const inner = toYaml(item, indent + 1);
          const lines = inner.split('\n');
          return `${pad}- ${lines[0].trimStart()}\n${lines.slice(1).join('\n')}`;
        }
        return `${pad}- ${toYaml(item, 0)}`;
      })
      .join('\n');
  }
  const keys = Object.keys(value);
  if (!keys.length) return '{}';
  return keys
    .map((k) => {
      const v = value[k];
      if (v && typeof v === 'object' && !Array.isArray(v)) {
        return `${pad}${k}:\n${toYaml(v, indent + 1)}`;
      }
      if (Array.isArray(v)) {
        if (!v.length) return `${pad}${k}: []`;
        return `${pad}${k}:\n${toYaml(v, indent + 1)}`;
      }
      return `${pad}${k}: ${toYaml(v, 0)}`;
    })
    .join('\n');
}

function definition(saga, steps, services) {
  const svc = (id) => services.find((s) => s.id === id);
  return {
    apiVersion: 'sagaforge.dev/v1',
    kind: 'Saga',
    metadata: {
      name: saga.name,
      id: saga.id,
      pattern: saga.pattern,
      status: saga.status,
      description: saga.description || '',
    },
    spec: {
      steps: steps.map((st) => ({
        order: st.step_order,
        name: st.name,
        service: svc(st.service_id)?.slug || svc(st.service_id)?.name || 'unknown',
        action: st.action,
        onSuccess: st.event_success,
        onFailure: st.event_failure,
        compensate: st.compensate_action,
        timeoutMs: st.timeout_ms,
        retries: st.retry_count,
        payloadSchema: safeJson(st.payload_schema),
      })),
    },
  };
}

function safeJson(raw) {
  if (!raw) return {};
  if (typeof raw === 'object') return raw;
  try { return JSON.parse(raw); } catch { return { raw: String(raw) }; }
}

function javaSource(saga, steps, services) {
  const cls = ident(saga.name) + 'Saga';
  const svc = (id) => services.find((s) => s.id === id);
  const methods = steps.map((st) => {
    const m = camel(st.action || st.name);
    const c = camel(st.compensate_action || ('compensate ' + st.name));
    const service = svc(st.service_id);
    return `
    /**
     * Step ${st.step_order}: ${st.name}
     * Service: ${service ? service.name : 'unassigned'} ${service ? '(' + service.endpoint + ')' : ''}
     * Success event: ${st.event_success || '—'}
     * Failure event: ${st.event_failure || '—'}
     */
    @SagaOrchestrationStart${st.step_order === 1 ? '' : ''}
    @EndState(on = "${st.event_success || (m + 'Succeeded')}")
    public void ${m}(${ident(st.name)}Command cmd) {
        log.info("Dispatch ${st.action || st.name} correlation={}", cmd.getCorrelationId());
        commandGateway.send(cmd);
    }

    @Compensate
    public void ${c}(${ident(st.name)}Command cmd) {
        log.warn("Compensate ${st.name} via ${st.compensate_action || 'rollback'}");
        commandGateway.send(new ${ident(st.compensate_action || ('Compensate ' + st.name))}Command(cmd.getCorrelationId()));
    }`;
  }).join('\n');

  return `package com.sagaforge.orchestration;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;
import io.eventuate.tram.sagas.orchestration.Saga;
import io.eventuate.tram.sagas.simpledsl.SimpleSaga;

/**
 * Generated by SagaForge — Event-Driven Microservices Saga Orchestrator
 * Saga: ${saga.name}
 * Pattern: ${saga.pattern}
 *
 * ${saga.description || 'Distributed transaction with compensating actions.'}
 *
 * Wire this orchestrator into a Spring Boot service that already has
 * Eventuate Tram / Axon / or your own command bus on the classpath.
 */
@Component
public class ${cls} implements SimpleSaga<${cls}Data> {
    private static final Logger log = LoggerFactory.getLogger(${cls}.class);
    private final CommandGateway commandGateway;

    public ${cls}(CommandGateway commandGateway) {
        this.commandGateway = commandGateway;
    }

    @Override
    public SagaDefinition<${cls}Data> getSagaDefinition() {
        return step()
${steps.map((st, i) => {
    const m = camel(st.action || st.name);
    const c = camel(st.compensate_action || ('compensate ' + st.name));
    const tail = i === steps.length - 1 ? '' : '\n';
    return `            .invokeParticipant(${cls}::${m})
                .withCompensation(${cls}::${c})${tail}`;
  }).join('')}
            .build();
    }
${methods}
}
`;
}

function tsSource(saga, steps, services) {
  const cls = ident(saga.name) + 'Saga';
  const svc = (id) => services.find((s) => s.id === id);
  const stepLit = steps.map((st) => {
    const service = svc(st.service_id);
    return `    {
      order: ${st.step_order},
      name: ${JSON.stringify(st.name)},
      service: ${JSON.stringify(service?.slug || 'unknown')},
      command: ${JSON.stringify(st.action || st.name)},
      onSuccess: ${JSON.stringify(st.event_success || '')},
      onFailure: ${JSON.stringify(st.event_failure || '')},
      compensate: ${JSON.stringify(st.compensate_action || '')},
      timeoutMs: ${st.timeout_ms || 5000},
      retries: ${st.retry_count || 0},
      async execute(ctx: SagaContext) {
        return ctx.bus.send(${JSON.stringify(st.action || st.name)}, ctx.payload);
      },
      async rollback(ctx: SagaContext) {
        return ctx.bus.send(${JSON.stringify(st.compensate_action || ('Compensate' + ident(st.name)))}, ctx.payload);
      },
    }`;
  }).join(',\n');

  return `/**
 * Generated by SagaForge — Event-Driven Microservices Saga Orchestrator
 * Saga: ${saga.name}
 * Pattern: ${saga.pattern}
 */
export type SagaStatus = 'pending' | 'running' | 'compensating' | 'completed' | 'failed' | 'compensated';

export interface SagaContext {
  correlationId: string;
  payload: Record<string, unknown>;
  bus: { send(event: string, payload: unknown): Promise<unknown> };
}

export interface SagaStep {
  order: number;
  name: string;
  service: string;
  command: string;
  onSuccess: string;
  onFailure: string;
  compensate: string;
  timeoutMs: number;
  retries: number;
  execute(ctx: SagaContext): Promise<unknown>;
  rollback(ctx: SagaContext): Promise<unknown>;
}

export const ${camel(saga.name)}Definition = {
  name: ${JSON.stringify(saga.name)},
  pattern: ${JSON.stringify(saga.pattern)} as 'orchestrated' | 'choreographed',
  description: ${JSON.stringify(saga.description || '')},
  steps: [
${stepLit}
  ] satisfies SagaStep[],
};

export class ${cls} {
  constructor(private readonly bus: SagaContext['bus']) {}

  async run(payload: Record<string, unknown>, correlationId = crypto.randomUUID()) {
    const ctx: SagaContext = { correlationId, payload, bus: this.bus };
    const done: SagaStep[] = [];
    try {
      for (const step of ${camel(saga.name)}Definition.steps) {
        await step.execute(ctx);
        done.push(step);
      }
      return { status: 'completed' as SagaStatus, correlationId };
    } catch (err) {
      for (const step of [...done].reverse()) {
        await step.rollback(ctx);
      }
      return { status: 'compensated' as SagaStatus, correlationId, error: String(err) };
    }
  }
}

export default ${cls};
`;
}

function mermaid(saga, steps, services) {
  const svc = (id) => {
    const s = services.find((x) => x.id === id);
    return (s?.name || 'Service').replace(/[^A-Za-z0-9]/g, '');
  };
  const names = Array.from(new Set(steps.map((st) => svc(st.service_id))));
  const lines = [
    'sequenceDiagram',
    '    autonumber',
    '    participant Orch as SagaForge Orchestrator',
    ...names.map((n) => `    participant ${n} as ${n}`),
    `    Note over Orch: ${saga.name} (${saga.pattern})`,
  ];
  steps.forEach((st) => {
    const n = svc(st.service_id);
    lines.push(`    Orch->>${n}: ${st.action || st.name}`);
    lines.push(`    ${n}-->>Orch: ${st.event_success || 'Succeeded'}`);
  });
  lines.push('    Note over Orch: On failure, compensate in reverse');
  [...steps].reverse().forEach((st) => {
    const n = svc(st.service_id);
    lines.push(`    Orch--x${n}: ${st.compensate_action || ('Compensate ' + st.name)}`);
  });

  const flow = [
    '',
    'flowchart LR',
    `    start([Start ${saga.name}]) --> s1`,
    ...steps.map((st, i) => {
      const id = 's' + (i + 1);
      const next = i === steps.length - 1 ? 'done([Completed])' : 's' + (i + 2);
      const fail = i === 0 ? 'fail([Failed])' : 'c' + i;
      return `    ${id}["${st.step_order}. ${st.name}"] -->|${st.event_success || 'ok'}| ${next}\n    ${id} -->|${st.event_failure || 'fail'}| ${fail}`;
    }),
    ...steps.slice(1).map((_, i) => {
      const idx = i + 1;
      const prev = idx === 1 ? 'fail([Failed])' : 'c' + (idx - 1);
      return `    c${idx}["Compensate ${steps[idx - 1].name}"] --> ${idx === 1 ? 'rolled([Compensated])' : 'c' + (idx - 1)}`.replace(prev, prev);
    }),
  ];

  return `%% Generated by SagaForge
%% ${saga.name} — ${saga.pattern}

${lines.join('\n')}
${flow.join('\n')}
`;
}

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  if (req.method === 'OPTIONS') return res.status(204).end();

  if (req.method !== 'GET') return res.status(405).json({ error: 'Method not allowed' });

  try {
    const { saga_id, format } = req.query;
    if (!saga_id) return res.status(400).json({ error: 'saga_id is required' });
    const fmt = String(format || 'json').toLowerCase();

    const { data: saga, error } = await supabase
      .from('sagaforge_sagas')
      .select('*')
      .eq('id', saga_id)
      .single();
    if (error || !saga) return res.status(404).json({ error: 'Saga not found' });

    const { data: steps } = await supabase
      .from('sagaforge_steps')
      .select('*')
      .eq('saga_id', saga_id)
      .order('step_order', { ascending: true });
    const { data: services } = await supabase.from('sagaforge_services').select('*');

    const def = definition(saga, steps || [], services || []);
    const slug = String(saga.name || 'saga').toLowerCase().replace(/[^a-z0-9]+/g, '-');
    const pack = {
      json: { filename: `${slug}.saga.json`, mime: 'application/json', content: JSON.stringify(def, null, 2) },
      yaml: { filename: `${slug}.saga.yaml`, mime: 'text/yaml', content: toYaml(def) + '\n' },
      java: { filename: `${ident(saga.name)}Saga.java`, mime: 'text/x-java-source', content: javaSource(saga, steps || [], services || []) },
      typescript: { filename: `${ident(saga.name)}Saga.ts`, mime: 'text/typescript', content: tsSource(saga, steps || [], services || []) },
      mermaid: { filename: `${slug}.mmd`, mime: 'text/plain', content: mermaid(saga, steps || [], services || []) },
    };

    if (fmt === 'all') {
      return res.status(200).json({
        saga: saga.name,
        artifacts: Object.fromEntries(Object.entries(pack).map(([k, v]) => [k, v])),
      });
    }
    if (!pack[fmt]) return res.status(400).json({ error: 'format must be json, yaml, java, typescript, mermaid, or all' });
    return res.status(200).json(pack[fmt]);
  } catch (err) {
    console.error('export API error:', err);
    res.status(500).json({ error: err.message });
  }
}
